
- name: Extract artifact.tar.gz
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: $HOME/

- name: Executing node
  become: yes
  ansible.builtin.shell: |
    echo $TYPEORM_CONNECTION2 >> text.txt
    echo $TYPEORM_PORT >> text.txt
    npm install
    pm2 stop default  
    pm2 start npm -- start
  register: print_result

- name: Debug Executing node
  debug:
    msg: "{{ print_result.stdout_lines }}"