
- name: Extract artifact.tar.gz
  ansible.builtin.unarchive:
    src: files/artifact.tar.gz
    dest: $HOME/

- name: Executing node
  become: yes
  ansible.builtin.shell: |
    pm2 start npm -- start
  register: print_result