
# - name: update apt package
#   become: yes
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
    
- name: Print NVM version
  become: no
  ansible.builtin.shell: >
    . $HOME/.nvm/nvm.sh && nvm --version
  args:
    executable: /bin/bash
    chdir: $HOME


- name: "install python for Ansible."
  become: yes
  apt:
    name: ["python3", "pip"]
    state: latest
    update_cache: yes

- name: "install Node and Npm for Ansible."
  become: yes
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes


- name: Print NPM version
  ansible.builtin.shell: npm --version
  args:
    executable: /bin/bash
    chdir: $HOME

- name: Install node
  become: no
  ansible.builtin.shell: >
    . $HOME/.nvm/nvm.sh && nvm install {{ item }} 
  args:
    executable: /bin/bash
    chdir: $HOME
    creates: $HOME/.nvm/versions/{{ item }}
  loop:
    - 13.8

- name: Print NPM version
  become: no
  ansible.builtin.shell: >
    . $HOME/.nvm/nvm.sh && nvm ls && node -v && echo $TYPEORM_PORT
  register: print_result
  args:
    executable: /bin/bash
    chdir: $HOME

- name: set Default node 13.8
  become: no
  ansible.builtin.shell: >
    . $HOME/.nvm/nvm.sh && nvm alias default 13.8 &&  nvm use default
  args:
    executable: /bin/bash
    chdir: $HOME

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Debug Executing node
  debug:
    msg: "{{ print_result.stdout }}."

- name: exit sucess
  ansible.builtin.shell: exit 0